
package food_project;

import food_project2.Home;
import javax.swing.JOptionPane;

/**
 *
 * @author khushi pandey
 */
public class Admin_Panel extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Panel
     */
    public Admin_Panel() {
        this.setExtendedState(Home.MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rest_details = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        customer_details = new javax.swing.JButton();
        income_details = new javax.swing.JButton();
        employee_details = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rest_details.setBackground(new java.awt.Color(255, 0, 0));
        rest_details.setFont(new java.awt.Font("Myanmar Text", 1, 22)); // NOI18N
        rest_details.setForeground(new java.awt.Color(255, 255, 255));
        rest_details.setText("Total No. of Restaraunts");
        rest_details.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rest_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rest_detailsActionPerformed(evt);
            }
        });
        getContentPane().add(rest_details, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 320, 120));
        rest_details.getAccessibleContext().setAccessibleDescription("");

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 29)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Welcome ,");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Sanskrit Text", 1, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("To This Page");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 180, -1));

        customer_details.setBackground(new java.awt.Color(0, 0, 255));
        customer_details.setFont(new java.awt.Font("Myanmar Text", 1, 22)); // NOI18N
        customer_details.setForeground(new java.awt.Color(255, 255, 255));
        customer_details.setText("Customer Details");
        customer_details.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        customer_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_detailsActionPerformed(evt);
            }
        });
        getContentPane().add(customer_details, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 320, 120));

        income_details.setBackground(new java.awt.Color(255, 0, 204));
        income_details.setFont(new java.awt.Font("Myanmar Text", 1, 22)); // NOI18N
        income_details.setForeground(new java.awt.Color(255, 255, 255));
        income_details.setText("Restaurant Income Details");
        income_details.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        income_details.setDefaultCapable(false);
        income_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                income_detailsActionPerformed(evt);
            }
        });
        getContentPane().add(income_details, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 490, 320, 120));

        employee_details.setBackground(new java.awt.Color(0, 204, 102));
        employee_details.setFont(new java.awt.Font("Myanmar Text", 1, 22)); // NOI18N
        employee_details.setForeground(new java.awt.Color(255, 255, 255));
        employee_details.setText("Employees Details");
        employee_details.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        employee_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employee_detailsActionPerformed(evt);
            }
        });
        getContentPane().add(employee_details, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 230, 320, 120));

        Back.setBackground(new java.awt.Color(204, 204, 204));
        Back.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 20, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(32, 163, 103));
        jLabel7.setText("K - Food");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 190, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rest_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rest_detailsActionPerformed
         JOptionPane.showMessageDialog(rootPane, "Welecome in Restaurant Details Page!");
                // Open your Admin_Panel here
                 Rest_Details details_rest = new  Rest_Details();
                 details_rest.setVisible(true);
    }//GEN-LAST:event_rest_detailsActionPerformed

    private void employee_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employee_detailsActionPerformed
         Employee_Panel emp = new Employee_Panel();
         emp.setVisible(true);
    }//GEN-LAST:event_employee_detailsActionPerformed

    private void customer_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_detailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_detailsActionPerformed

    private void income_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_income_detailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_income_detailsActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
          this.dispose(); // Terminate the current JFrame
        Login_Form login = new Login_Form(); // Create an instance of the Employee_Panel class
        login.setVisible(true); // Make the Employee_Panel visible
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton customer_details;
    private javax.swing.JButton employee_details;
    private javax.swing.JButton income_details;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton rest_details;
    // End of variables declaration//GEN-END:variables
}
