/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package food_project;
import food_project2.conn;
import food_project2.Home;
import java.sql.*;
import com.toedter.calendar.JDateChooser; // Import the JCalendar componen
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class Emp_add extends javax.swing.JFrame {
     Connection con = null;
   ResultSet rs = null;
   PreparedStatement ps = null;
   
     private final JDateChooser emp_dob_calendar; 
      private final JDateChooser emp_doj_calendar;
    public Emp_add() {
        con = conn.mycon();  
        this.setExtendedState(Home.MAXIMIZED_BOTH);
        initComponents();
        String[] educationOptions = {"Select", "B.Sc", "MBA", "B.E", "M.E", "B.Acc", "M.Fin", "B.Mktg", "M.Psy", "B.Nur",
            "M.Ed", "B.Comm", "M.PH", "B.CJ", "M.SW", "B.GD", "M.IT", "B.Bio", "M.Env", "B.Eng", 
            "M.PS", "B.Hist", "M.Soc", "B.Math", "M.IR", "High School", "Intermediate", 
            "B.A", "B.Com", "B.Tech", "M.Tech", "BBA", "MCA", "BCA", "MS", "Ph.D", 
            "LLB", "BDS", "MBBS", "CA", "ICWA", "CS", "M.Sc", "M.A", "BFA", "B.Pharm",
            "M.Pharm", "B.Ed", "Diploma"};
      DefaultComboBoxModel<String> eduModel = new DefaultComboBoxModel<>(educationOptions);
      emp_edu.setModel(eduModel);
      emp_edu = new javax.swing.JComboBox<>(eduModel);
      emp_edu.setFont(new java.awt.Font("Segoe UI", 1, 14));
      // Set font for combo box
      getContentPane().add(emp_edu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 460, 160, -1));
     emp_dob_calendar = new JDateChooser(); // Initialize the JDateChooser
      getContentPane().add(emp_dob_calendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, 190, -1)); // Add JDateChooser
        // Add a JDateChooser component for emp_doj after emp_salary in the initComponents method
   emp_doj_calendar = new JDateChooser();
    getContentPane().add(emp_doj_calendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 390, 190, -1)); // Adjust the coordinates as needed

// Adjust the submitActionPerformed method to retrieve the selected date from the JDateChooser for emp_doj
      String DOJ = ((JTextField) emp_doj_calendar.getDateEditor().getUiComponent()).getText();
        emp_id.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emp_n7 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel11 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        post = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        salary = new javax.swing.JLabel();
        edu = new javax.swing.JLabel();
        doj = new javax.swing.JLabel();
        father = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        emp_edu = new javax.swing.JComboBox<>();
        emp_post = new javax.swing.JTextField();
        emp_phone = new javax.swing.JTextField();
        emp_email = new javax.swing.JTextField();
        emp_add = new javax.swing.JTextField();
        emp_gender = new javax.swing.JTextField();
        emp_id = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        emp_name1 = new javax.swing.JTextField();
        emp_salary = new javax.swing.JTextField();
        back = new javax.swing.JButton();

        emp_n7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emp_n7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_n7ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setText("New Employee Details");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, -1, -1));

        name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(0, 0, 255));
        name.setText("Employee Name");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 149, -1));

        address.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        address.setForeground(new java.awt.Color(0, 0, 255));
        address.setText("Address");
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 149, -1));

        dob.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dob.setForeground(new java.awt.Color(0, 0, 255));
        dob.setText("Date Of Birth");
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 149, -1));

        post.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        post.setForeground(new java.awt.Color(0, 0, 255));
        post.setText("Post/ Desingnation");
        getContentPane().add(post, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 540, 170, -1));

        email.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        email.setForeground(new java.awt.Color(0, 0, 255));
        email.setText("Email ID");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 149, -1));

        id.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        id.setForeground(new java.awt.Color(0, 0, 255));
        id.setText("Employee ID");
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 170, 149, -1));

        phone.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        phone.setForeground(new java.awt.Color(0, 0, 255));
        phone.setText("Phone no.");
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 149, -1));

        salary.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        salary.setForeground(new java.awt.Color(0, 0, 255));
        salary.setText("Salary");
        getContentPane().add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 320, 149, -1));

        edu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        edu.setForeground(new java.awt.Color(0, 0, 255));
        edu.setText("Higher Qualification");
        getContentPane().add(edu, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 460, 180, -1));

        doj.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        doj.setForeground(new java.awt.Color(0, 0, 255));
        doj.setText("Date Of Joining");
        getContentPane().add(doj, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 390, 149, -1));

        father.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        father.setForeground(new java.awt.Color(0, 0, 255));
        father.setText("Father's Name");
        getContentPane().add(father, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 240, 149, -1));

        gender.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        gender.setForeground(new java.awt.Color(0, 0, 255));
        gender.setText("Gender");
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, 149, -1));

        submit.setBackground(new java.awt.Color(102, 204, 0));
        submit.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 640, -1, -1));

        cancel.setBackground(new java.awt.Color(255, 0, 51));
        cancel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 640, -1, -1));

        emp_edu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emp_edu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(emp_edu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 460, 160, -1));

        emp_post.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(emp_post, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 540, 190, -1));

        emp_phone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(emp_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 190, -1));

        emp_email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(emp_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 190, -1));

        emp_add.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(emp_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 190, -1));

        emp_gender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(emp_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 530, 190, -1));

        emp_id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(emp_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 170, 190, -1));

        jTextField9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 240, 190, -1));

        emp_name1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(emp_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 190, -1));

        emp_salary.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(emp_salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 310, 190, -1));

        back.setBackground(new java.awt.Color(204, 204, 204));
        back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emp_n7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_n7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_n7ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
           try {
        // Generate a random six-digit number for Employee_ID
        String Emloyee_Id = generateRandomSixDigitNumber();
        String Employee_name = emp_name1.getText(); // Corrected variable name
        String Father_Name = jTextField9.getText(); // Corrected variable name
        String DOB = ((JTextField) emp_dob_calendar.getDateEditor().getUiComponent()).getText(); // Corrected variable name
        String Phone_no = emp_phone.getText();
        String Emp_Address = emp_add.getText();
        String Emp_Salary = emp_salary.getText();
        String Email_ID = emp_email.getText();
        String Higher_Qua = emp_edu.getSelectedItem().toString();
        String Post = emp_post.getText();
        String Gender = emp_gender.getText(); // Assuming emp_gender is the component for gender input
        String DOJ = ((JTextField) emp_doj_calendar.getDateEditor().getUiComponent()).getText(); // Corrected variable name
        
        // Check if email contains "@gmail.com"
        if (!Email_ID.contains("@gmail.com")) {
            JOptionPane.showMessageDialog(null, "Please enter a valid Gmail address");
            return; // Stop further execution
        }
        if (Phone_no.length() != 10) {
            JOptionPane.showMessageDialog(null, "Please enter a 10-digit phone number");
            return; // Stop further execution
        }

        String query = "INSERT INTO employee_details (Emp_ID, Name, Father_Name, DOB, Phone_no, Address, Salary, Email_ID, Higher_edu, Post, Gender, DOJ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement pst = con.prepareStatement(query);
        
        pst.setString(1, Emloyee_Id);
        pst.setString(2, Employee_name);
        pst.setString(3, Father_Name);
        pst.setString(4,  DOB);
        pst.setString(5, Phone_no);
        pst.setString(6, Emp_Address);
        pst.setString(7, Emp_Salary);
        pst.setString(8, Email_ID);
        pst.setString(9, Higher_Qua);
        pst.setString(10, Post);
        pst.setString(11, Gender);
        pst.setString(12, DOJ);
        // Assuming Department and Experience are obtained from input fields as well
        
        pst.executeUpdate();
        
        JOptionPane.showMessageDialog(null, "Data Inserted Successfully!");
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_submitActionPerformed
    private String generateRandomSixDigitNumber() {
    Random random = new Random();
    int num = random.nextInt(900000) + 100000; // Generates a random number between 100000 and 999999
    return String.valueOf(num);
}

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // Clear all the text fields and reset the combo box to default
        emp_name1.setText("");
        jTextField9.setText("");
        emp_phone.setText("");
        emp_add.setText("");
        emp_salary.setText("");
        emp_email.setText("");
        emp_post.setText("");
        emp_gender.setText("");
        emp_edu.setSelectedIndex(0); // Set to default value
        emp_dob_calendar.setDate(null); // Clear the date chooser for DOB
        emp_doj_calendar.setDate(null); // Clear the date chooser for DOJ
    }//GEN-LAST:event_cancelActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
         this.dispose(); // Terminate the current JFrame
    Employee_Panel employeePanel = new Employee_Panel(); // Create an instance of the Employee_Panel class
    employeePanel.setVisible(true); // Make the Employee_Panel visible
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Emp_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Emp_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Emp_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Emp_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Emp_add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel dob;
    private javax.swing.JLabel doj;
    private javax.swing.JLabel edu;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emp_add;
    private javax.swing.JComboBox<String> emp_edu;
    private javax.swing.JTextField emp_email;
    private javax.swing.JTextField emp_gender;
    private javax.swing.JTextField emp_id;
    private javax.swing.JTextField emp_n7;
    private javax.swing.JTextField emp_name1;
    private javax.swing.JTextField emp_phone;
    private javax.swing.JTextField emp_post;
    private javax.swing.JTextField emp_salary;
    private javax.swing.JLabel father;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel name;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel post;
    private javax.swing.JLabel salary;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
