/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package food_project;

/**
 *
 * @author khushi pandey
 */
public class pane extends javax.swing.JFrame {

    /**
     * Creates new form pane
     */
    public pane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        girlschef = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        head = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        slide_imgs = new javax.swing.JLabel();
        manch = new javax.swing.JLabel();
        Nav = new javax.swing.JPanel();
        login_btn = new javax.swing.JButton();
        Register_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        choise = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main.setBackground(new java.awt.Color(102, 102, 102));
        main.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        main.setForeground(new java.awt.Color(102, 102, 102));
        main.setLayout(null);

        jTextArea2.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. \"\n        + \"Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, \"\n        + \"quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. \"\n        + \"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. \"\n        + \"Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
        jTextArea2.setBorder(null);
        jScrollPane2.setViewportView(jTextArea2);

        main.add(jScrollPane2);
        jScrollPane2.setBounds(410, 830, 750, 230);

        girlschef.setForeground(new java.awt.Color(255, 255, 255));
        girlschef.setIcon(new javax.swing.ImageIcon("E:\\Food\\file2.png")); // NOI18N
        main.add(girlschef);
        girlschef.setBounds(1210, 730, 236, 390);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setForeground(new java.awt.Color(0, 204, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        head.setBackground(new java.awt.Color(204, 0, 204));
        head.setFont(new java.awt.Font("Palatino Linotype", 3, 23)); // NOI18N
        head.setForeground(new java.awt.Color(255, 255, 255));
        head.setText("Get And Order All Delicious Food Here");
        jPanel2.add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, -40, -1, -1));

        main.add(jPanel2);
        jPanel2.setBounds(0, 0, 1570, 50);
        main.add(slide_imgs);
        slide_imgs.setBounds(0, 60, 1530, 650);

        manch.setForeground(new java.awt.Color(255, 255, 255));
        manch.setIcon(new javax.swing.ImageIcon("E:\\Food\\file.png")); // NOI18N
        main.add(manch);
        manch.setBounds(30, 970, 340, 380);

        getContentPane().add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1600, 2050));

        Nav.setBackground(new java.awt.Color(204, 204, 0));
        Nav.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Nav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login_btn.setBackground(new java.awt.Color(51, 51, 255));
        login_btn.setFont(new java.awt.Font("SimSun-ExtB", 1, 15)); // NOI18N
        login_btn.setForeground(new java.awt.Color(255, 255, 255));
        login_btn.setText("Login");
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });
        Nav.add(login_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 10, 80, 25));

        Register_btn.setBackground(new java.awt.Color(0, 204, 0));
        Register_btn.setFont(new java.awt.Font("SimSun", 1, 15)); // NOI18N
        Register_btn.setForeground(new java.awt.Color(255, 255, 255));
        Register_btn.setText("Register");
        Register_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_btnActionPerformed(evt);
            }
        });
        Nav.add(Register_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, 100, 25));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setText("OR");
        Nav.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 10, -1, -1));

        choise.setBackground(new java.awt.Color(204, 204, 255));
        choise.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 14)); // NOI18N
        choise.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        choise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiseActionPerformed(evt);
            }
        });
        Nav.add(choise, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 20));
        Nav.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, -40, -1, -1));

        getContentPane().add(Nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1580, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_btnActionPerformed

    private void Register_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Register_btnActionPerformed

    private void choiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiseActionPerformed
        String selectedOption = (String) choise.getSelectedItem();
        if (selectedOption.equals("Veg")) {
            // Open Menu1 JFrame for Veg
            //        Menu1 menu1 = new Menu1(id);
            //        menu1.setVisible(true);
        } else if (selectedOption.equals("Non-Veg")) {
            //        // Open Menu2 JFrame for Non-Veg
            //        Menu2 menu2 = new Menu2();
            //        menu2.setVisible(true);
        }
    }//GEN-LAST:event_choiseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pane().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Nav;
    private javax.swing.JButton Register_btn;
    private javax.swing.JComboBox<String> choise;
    private javax.swing.JLabel girlschef;
    private javax.swing.JLabel head;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton login_btn;
    private javax.swing.JPanel main;
    private javax.swing.JLabel manch;
    private javax.swing.JLabel slide_imgs;
    // End of variables declaration//GEN-END:variables
}
